            - name: PyPI Auto Publish
  # You may pin to the exact commit or the version.
  # uses: AlirezaTheH/pypi-auto-publish@508a2937b5a2abc343c2df471d824eb74af98551
  uses: AlirezaTheH/pypi-auto-publish@v1.0.0
  with:
    # API token of the Test PyPI account publishing the project. If missing, publish on Test PyPI is skipped.
    test-pypi-api-token: # optional
    # API token of the PyPI account publishing the project.
    pypi-api-token: pypi-AgENdGVzdC5weXBpLm9yZwIkNjU5ZGZjOTktOTJlZS00OGVlLWEyMTctNTEzMjczYWFhMGYwAAIqWzMsImFjYzJmNzA1LTRmM2UtNDdkOS1iMGEzLTliNjZkNjc5YzRmYiJdAAAGIJx5o-ku5-iig1hPnmwr1OEbB10VaThTTtTsRnqAVsN0
    # Name of the PyPI package.
    package-name: MailPilot
          
